### ISSUE TITLE
CSS main (Home)

### ISSUE THREAD

**Issue by linuxonrails** [jbernach/transandalus#3]
https://projects.invisionapp.com/share/2X8YVIWDW#/screens/197332378_01a_Home

https://trello-attachments.s3.amazonaws.com/569f38763b04b0f444fa93b4/56cd6a586549cef078bb15f6/a2f45c621ebe5d6156d1bf32da6f2f52/01a_Home.png
https://www.dropbox.com/s/6x81jyho2hvtna8/01b_Home_Hover.png?dl=0
https://www.dropbox.com/s/kr33g6lokot9zbk/01a_Home.png?dl=0

**Comment by jbernach** [comment]
Hola,

no entiendo muy bien a lo que te refieres.

Yo utilizaría esta herramienta para gestionarlo todo por temas de integración, aparte de que no conozco las demás.

Ahora mismo hay un prototipo que solo sirve para:
- tener la estructura base del proyecto, con el workflow en Grunt, las dependencias en Bower etc.
- tener el módulo Angular de la aplicación y la configuración del router, de las traducciones y directivas varias.
- tener servicios para acceder al API de la transandalus ya hechos, con ejemplos de acceso.

Digamos que es un punto de partida con funcionalidad que sirve de base y ejemplo.

Ahora habría que ver cómo queda el diseño e implementarlo.

No estoy seguro de hecho de si aún es pronto para empezar a trabajar en el front hasta que Beatriz haya terminado.

Desde luego comenzar a adaptar este prototipo ahora como ejercicio para familiarizarte me parece perfecto ;-)

Podríamos crear un tablero en Trello para la web exclusivamente. Yo tengo uno para la parte de administración que me sirve para organizarme.

Un saludo.

**Comment by linuxonrails** [comment]
EMHO el sistema de gestión de tareas de github funciona muy bien para tareas finales de cambios al código: https://github.com/jbernach/transandalus/projects (prueba a crear a añadir un proyecto y crear varias columnas para tareas:  Backlog, Next, InProgress, PR y Done)

Mira este ejemplillo de un proyecto para aprender React: 
https://github.com/Lemoncode/react-by-sample/projects/1

**Comment by jbernach** [comment]
Perdona, pero me llega este correo y estoy perdido...

**Comment by linuxonrails** [comment]
No me deja hacer un push de mi rama.

remote: Permission to jbernach/transandalus.git denied to linuxonrails.
fatal: unable to access 'https://github.com/jbernach/transandalus/': The requested URL returned error: 403

Tendré que trabajar con forks.

**Comment by jbernach** [comment]
He aceptado el pr. Creo que esta es la mejor forma de trabajar.
